[sandbox]
image = "debian:latest"
agent = "IS_SANDBOX=1 claude --dangerously-skip-permissions"
shell = "bash"
user = "coop"

setup = [
  "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y bash curl git ca-certificates",
]

mounts = [
  "~/.bashrc:~/.bashrc",             # for bash configuration
  "~/.local/claude:~/.local/claude", # use local claude binary
  "claude-config:~/.claude",         # for claude configuration
]
